[codelinks]
# Configuration for source tracing
set_local_url = false            # Set to true to enable local code html and URL generation
local_url_field = "local-url"   # Need's field name for local URL
set_remote_url = true           # Set to true to enable remote url to be generated
remote_url_field = "remote-url" # Need's field name for remote URL


[codelinks.projects.src]
remote_url_pattern = "https://github.com/PhilipPartsch/Sphinx2Code/blob/{commit}/{path}#L{line}"

[codelinks.projects.src.source_discover]
src_dir = "../tests/doc_test/minimum_config"
